### ISSUE TITLE
The CMAKE_FORCE_CXX_COMPILER macro is deprecated

### ISSUE THREAD

**Issue by zmjios** [cristeab/ios-cmake#10]
The CMAKE_FORCE_CXX_COMPILER macro is deprecated.  Instead just set
  CMAKE_CXX_COMPILER and allow CMake to identify the compiler.
Call Stack (most recent call first):
  toolchain/iOS.cmake:51 (CMAKE_FORCE_CXX_COMPILER)
  build.ios/CMakeFiles/3.7.1/CMakeSystem.cmake:6 (include)
  CMakeLists.txt

**Comment by tyym1314** [comment]
#these two lines
#CMAKE_FORCE_C_COMPILER (gcc gcc)
#CMAKE_FORCE_CXX_COMPILER (g++ g++)
and add the below:
set(CMAKE_C_COMPILER /usr/bin/clang)
set(CMAKE_CXX_COMPILER /usr/bin/clang++)
mention:not clang ,is /usr/bin/clang  "whereis clang " in terminal can get the path

**Comment by kooqilylb** [comment]
what about this issue processing ?

**Comment by cristeab** [comment]
Should be fixed now

**Comment by wuhyimu** [comment]
what about this issue processing ?I encountered the same problem，thank `you！`
