### ISSUE TITLE
All of header files not found

### ISSUE THREAD

**Issue by MinorUncle** [cristeab/ios-cmake#12]
I'm sure "CMAKE_IOS_DEVELOPER_ROOT" is set correctly，but all header files are not found in logs. 

the build commond like this:
 cmake -DCMAKE_TOOLCHAIN_FILE=../iOS.cmake  -DCMAKE_IOS_DEVELOPER_ROOT=/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/  -GXcode ..

the logs like this:
- Toolchain using default iOS SDK: /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk
-- The C compiler identification is AppleClang 9.0.0.9000039
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - failed
-- Detecting C compile features
-- Detecting C compile features - failed
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Could NOT find Git (missing: GIT_EXECUTABLE) 
-- Performing Test check_c_compiler_flag__Wno_error_deprecated_declarations
-- Performing Test check_c_compiler_flag__Wno_error_deprecated_declarations - Failed
-- Performing Test check_c_compiler_flag__Qunused_arguments
-- Performing Test check_c_compiler_flag__Qunused_arguments - Failed
-- Looking for __GNU_LIBRARY__
-- Looking for __GNU_LIBRARY__ - not found
-- Looking for _GNU_SOURCE
-- Looking for _GNU_SOURCE - not found
-- Looking for sys/types.h
-- Looking for sys/types.h - not found
-- Looking for sys/socket.h
-- Looking for sys/socket.h - not found
-- Looking for netinet/in.h
-- Looking for netinet/in.h - not found
... ...

**Comment by AlexandrSerzhantov** [comment]
Hi! I have the same problem with zlib and XCode 9 in my project. How did you solve it?
logs look the same:
-- Building with Xcode version: 9.2
-- Configuring iOS build for platform: OS, architecture(s): armv7;armv7s;arm64
-- Using SDK: /Applications/Xcode2.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.2.sdk for platform: OS
-- The C compiler identification is AppleClang 9.0.0.9000039
-- The CXX compiler identification is AppleClang 9.0.0.9000039
...
-- Looking for sys/types.h
-- Looking for sys/types.h - not found
-- Looking for stdint.h
-- Looking for stdint.h - not found
-- Looking for stddef.h
-- Looking for stddef.h - not found
...
