### ISSUE TITLE
  No iOS SDK's found in default search path

### ISSUE THREAD

**Issue by lengqingfeng** [cristeab/ios-cmake#8]
CMake Error at /Users/allen/Desktop/ios-cmake/toolchain/iOS.cmake:149 (message):
  No iOS SDK's found in default search path
  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk.

**Comment by tyym1314** [comment]
the before:
# Setup iOS developer location
if (NOT DEFINED CMAKE_IOS_DEVELOPER_ROOT)
	set (CMAKE_IOS_DEVELOPER_ROOT "/Developer/Platforms/${IOS_PLATFORM_LOCATION}/Developer")
modify "/Developer/Platforms/${IOS_PLATFORM_LOCATION}/Developer" to "/Applications/Xcode.app/Contents/Developer/Platforms/${IOS_PLATFORM_LOCATION}/Developer" can solve your problem ,if not ,check if you have "-DIOS_PLATFORM=OS" when cmake
